AspNetCoreIdentityApp.Web/Areas/Admin/Models/AssignRoleToUserViewModel.cs
namespace AspNetCoreIdentityApp.Web.Areas.Admin.Models
{
    public class AssignRoleToUserViewModel
    {
        public string Id { get; set; } = null!;
        public string Name { get; set; } = null!;
        public bool Exist { get; set; }
    }
}

AspNetCoreIdentityApp.Web/Areas/Admin/Models/RoleCreateViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreIdentityApp.Web.Areas.Admin.Models
{
    public class RoleCreateViewModel
    {
        [Required(ErrorMessage = "Role isim alanı boş bırakılamaz.")]
        [Display(Name = "Rol İsim : ")]
        public string Name { get; set; } = null!;
    }
}

AspNetCoreIdentityApp.Web/Areas/Admin/Models/RoleUpdateViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreIdentityApp.Web.Areas.Admin.Models
{
    public class RoleUpdateViewModel
    {
        public string Id { get; set; } = null!;
        [Required(ErrorMessage = "Role isim alanı boş bırakılamaz.")]
        [Display(Name = "Rol İsim : ")]
        public string Name { get; set; } = null!;
    }
}

AspNetCoreIdentityApp.Web/Areas/Admin/Models/RoleViewModel.cs
namespace AspNetCoreIdentityApp.Web.Areas.Admin.Models
{
    public class RoleViewModel
    {
        public string Id { get; set; } = null!;
        public string Name { get; set; } = null!;
    }
}

AspNetCoreIdentityApp.Web/Areas/Admin/Controllers/RolesController.cs
using AspNetCoreIdentityApp.Web.Areas.Admin.Models;
using AspNetCoreIdentityApp.Web.Extensions;
using AspNetCoreIdentityApp.Repository.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AspNetCoreIdentityApp.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    [Area("Admin")]
    public class RolesController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<AppRole> _roleManager;
        public RolesController(UserManager<AppUser> userManager, RoleManager<AppRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }
        [Authorize(Roles = "role-action")]
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.Select(x => new RoleViewModel()
            {
                Id = x.Id,
                Name = x.Name!
            }).ToListAsync();
            return View(roles);
        }
        [Authorize(Roles = "role-action")]
        public IActionResult RoleCreate()
        {

            return View();
        }
        [Authorize(Roles = "role-action")]
        [HttpPost]
        public async Task<IActionResult> RoleCreate(RoleCreateViewModel request)
        {
            var result = await _roleManager.CreateAsync(new AppRole()
            {
                Name = request.Name,
            });

            if (!result.Succeeded)
            {
                ModelState.AddModelErrorList(result.Errors);
                return View();
            }
            TempData["SuccessMessage"] = "Rol oluşturulmuştur.";
            return RedirectToAction(nameof(RolesController.Index));
        }
        [Authorize(Roles = "role-action")]
        public async Task<IActionResult> RoleUpdate(string id)
        {
            var roleToUpdate = await _roleManager.FindByIdAsync(id);

            if (roleToUpdate == null)
            {
                throw new Exception("Güncellenecek bir rol bulunamamıştır.");
            }
            return View(new RoleUpdateViewModel() { Id = roleToUpdate.Id, Name = roleToUpdate!.Name! });
        }
        [Authorize(Roles = "role-action")]
        [HttpPost]
        public async Task<IActionResult> RoleUpdate(RoleUpdateViewModel request)
        {
            var roleToUpdate = await _roleManager.FindByIdAsync(request.Id);

            if (roleToUpdate == null)
            {
                throw new Exception("Güncellenecek bir rol bulunamamıştır.");
            }

            roleToUpdate.Name = request.Name;
            await _roleManager.UpdateAsync(roleToUpdate);

            ViewData["SuccessMessage"] = "Rol bilgisi güncellendi";

            return View();
        }
        [Authorize(Roles = "role-action")]
        public async Task<IActionResult> RoleDelete(string id)
        {
            var roleToDelete = await _roleManager.FindByIdAsync(id);
            if (roleToDelete == null)
            {
                throw new Exception("Silinecek bir rol bulunamamıştır.");
            }

            var result = await _roleManager.DeleteAsync(roleToDelete);

            if (!result.Succeeded)
            {
                throw new Exception(result.Errors.Select(x => x.Description).First());
            }
            TempData["SuccessMessage"] = "Rol silinmiştir.";
            return RedirectToAction(nameof(RolesController.Index));
        }
        public async Task<IActionResult> AssignRoleToUser(string id)
        {
            var currentUser = (await _userManager.FindByIdAsync(id))!;
            ViewBag.userId = id;
            var roles = await _roleManager.Roles.ToListAsync();
            var userRoles = await _userManager.GetRolesAsync(currentUser);

            var roleViewModelList = new List<AssignRoleToUserViewModel>();



            foreach (var role in roles)
            {
                var assignRoleToViewModel = new AssignRoleToUserViewModel() { Id = role.Id, Name = role.Name! };

                if (userRoles.Contains(role.Name!))
                {
                    assignRoleToViewModel.Exist = true;
                }

                roleViewModelList.Add(assignRoleToViewModel);
            }


            return View(roleViewModelList);
        }
        [HttpPost]
        public async Task<IActionResult> AssignRoleToUser(string userId, List<AssignRoleToUserViewModel> requestList)
        {
            var userToAssignRoles = (await _userManager.FindByIdAsync(userId))!;
            foreach (var role in requestList)
            {
                if (role.Exist)
                {
                    await _userManager.AddToRoleAsync(userToAssignRoles, role.Name);
                }
                else
                {
                    await _userManager.RemoveFromRoleAsync(userToAssignRoles, role.Name);
                }
            }
            return RedirectToAction(nameof(HomeController.UserList), "Home");
        }
    }
}

AspNetCoreIdentityApp.Web/Areas/Admin/Views/Roles/AssignRoleToUser.cshtml
@{
    ViewData["Title"] = "AssignRoleToUser";
}
@model List<AdminModel.AssignRoleToUserViewModel>

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h2>Kullanıcıya Rol Atama</h2>
        <form asp-action="AssignRoleToUser" asp-route-userId="@ViewBag.userId" method="post">
            @for (int i = 0; i < Model.Count; i++)
            {
                <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" asp-for="@Model[i].Exist">
                    <label class="form-check-label" asp-for="@Model[i].Exist">@Model[i].Name</label>
                    <input type="hidden" asp-for="@Model[i].Name" />
                    <input type="hidden" asp-for="@Model[i].Id" />
                </div>
            }
            <div class="form-group mt-3">
                <input type="submit" value="Rol Ata" class="btn btn-primary"/>
            </div>
        </form>
        <div class="mt-3">
            <a asp-controller="Home" asp-action="UserList">Kullanıcı Listesine Geri Dön</a>
        </div>
    </div>
</div>

AspNetCoreIdentityApp.Web/Areas/Admin/Views/Roles/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model List<AdminModel.RoleViewModel>

<div class="row">
    <div class="col-md-6 offset-md-2">
        <h2>Roler</h2>
    </div>
    <div class="col-md-2">
        <a class="btn btn-primary" asp-controller="Roles" asp-action="RoleCreate" asp-area="admin">Rol Ekle</a>
    </div>
</div>
<div class="row">
    
    <div class="col-md-8 offset-md-2">
        @if (TempData["SuccessMessage"] != null)
        {
            <div class="alert alert-info" role="alert">
                @TempData["SuccessMessage"]
            </div>
        }
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Role İsmi</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Name</td>
                        <td>
                            <a class="btn btn-dark btn-sm" asp-area="admin" asp-controller="Roles" asp-action="RoleUpdate" asp-route-id="@item.Id">Rol Güncelle</a>
                            <a class="btn btn-dark btn-sm my-1" asp-area="admin" asp-controller="Roles" asp-action="RoleDelete" asp-route-id="@item.Id">Rol Sil</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

AspNetCoreIdentityApp.Web/Areas/Admin/Views/Roles/RoleCreate.cshtml
@model AdminModel.RoleCreateViewModel

@{
    ViewData["Title"] = "RoleCreate";
}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h2>Role Oluşturma</h2>
        <form asp-action="RoleCreate" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Oluştur" class="btn btn-primary" />
            </div>
        </form>
        <div class="mt-3">
            <a asp-action="Index">Role Listesine Geri Dön</a>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AspNetCoreIdentityApp.Web/Areas/Admin/Views/Roles/RoleUpdate.cshtml
@{
    ViewData["Title"] = "RoleUpdate";
}
@model AdminModel.RoleUpdateViewModel

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h2>Role Oluşturma</h2>
        @if (ViewData["SuccessMessage"] != null)
        {
            <div class="alert alert-info" role="alert">
                @ViewData["SuccessMessage"]
            </div>
        }
        <form asp-action="RoleUpdate" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id"/>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Güncelle" class="btn btn-primary" />
            </div>
        </form>
        <div class="mt-3">
            <a asp-action="Index">Role Listesine Geri Dön</a>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}